name: 'Build WebAPI'
description: 'Build and publish .NET WebAPI project'
inputs:
  dotnet-version:
    description: 'The version of .NET to use'
    required: true
    default: '8.0.x'
  project-path:
    description: 'Project path'
    required: true
    default: './src/MyWebApi'

runs:
  using: 'composite'
  steps:
    - name: Check out repo code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore
      run: dotnet restore ${{ inputs.project-path }}
      shell: bash

    - name: Build
      run: dotnet build ${{ inputs.project-path }} --configuration Release --no-restore
      shell: bash

